services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  postgres_network:
    driver: bridge